// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4I54E-IfGuokC12adDsVHUm82dvbhghs',
    appId: '1:909599138209:web:1882c7ed494b480d30abe0',
    messagingSenderId: '909599138209',
    projectId: 'mesclainvest-5ee48',
    authDomain: 'mesclainvest-5ee48.firebaseapp.com',
    storageBucket: 'mesclainvest-5ee48.firebasestorage.app',
    measurementId: 'G-QQLZK4E41T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2IYTCFS4XG01ce65PkSwR6cER-2XrzA8',
    appId: '1:909599138209:android:84a473d2a15b811630abe0',
    messagingSenderId: '909599138209',
    projectId: 'mesclainvest-5ee48',
    storageBucket: 'mesclainvest-5ee48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLziOlpdXQcxMhpjcSU-38WYtYjXX_xmU',
    appId: '1:909599138209:ios:9aa4753f301e97d530abe0',
    messagingSenderId: '909599138209',
    projectId: 'mesclainvest-5ee48',
    storageBucket: 'mesclainvest-5ee48.firebasestorage.app',
    iosBundleId: 'com.example.mesclainvestf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLziOlpdXQcxMhpjcSU-38WYtYjXX_xmU',
    appId: '1:909599138209:ios:9aa4753f301e97d530abe0',
    messagingSenderId: '909599138209',
    projectId: 'mesclainvest-5ee48',
    storageBucket: 'mesclainvest-5ee48.firebasestorage.app',
    iosBundleId: 'com.example.mesclainvestf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4I54E-IfGuokC12adDsVHUm82dvbhghs',
    appId: '1:909599138209:web:2345c03c0e641f9430abe0',
    messagingSenderId: '909599138209',
    projectId: 'mesclainvest-5ee48',
    authDomain: 'mesclainvest-5ee48.firebaseapp.com',
    storageBucket: 'mesclainvest-5ee48.firebasestorage.app',
    measurementId: 'G-6YXGSDER4M',
  );
}
